blog/urls.py
from django.urls import path

from . import views

app_name = 'blog'

urlpatterns = [
    path('', views.index, name='index')
]

ppw_story/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('story_1/', include('story_1.urls')),
    path('', include('story_4.urls')),
    path('blog/', include('blog.urls')),
]

story_1/urls.py
from django.urls import path

from . import views

app_name = 'story_1'

urlpatterns = [
    path('', views.index, name='index')
]

story_4/urls.py
from django.urls import path

from . import views

app_name = 'story_4'

urlpatterns = [
    path('', views.index, name='index')
]

blog/models.py
from django.db import models

# Create your models here.

story_1/models.py
from django.db import models

# Create your models here.

story_4/models.py
from django.db import models

# Create your models here.

blog/views.py
from django.shortcuts import render

# Create your views here.
def index(request):
    return render(request, 'blog/index.html')

story_1/views.py
from django.shortcuts import render

# Create your views here.
def index(request):
    return render(request, 'story_1/index.html')

story_4/views.py
from django.shortcuts import render

# Create your views here.
def index(request):
    return render(request, 'story_4/index.html')

blog/templates/blog/index.html
{% extends 'blog/layout.html' %}
{% load static %}
{% block content %}
	    <div class="row">
	        <div class="col-12">
	            <div class="jumbotron p-3 p-md-5 rounded">
	                <div class="col-12" style="background-color: rgba(0,0,0, 0.4);">
	                    <h1 class="display-4 text-white">Reading is Your Superpower</h1>
	                    <p class="lead text-light my-3">Imagine if you can choose your own superpower. Which one do you choose? Flying may be useful and invisibility is okay for being naughty.
		                        But if you have the ability to read well, you'd be the most powerful person on the earth</p>
	                    <p class="lead mb-0"><a href="#" class="text-white font-weight-bold">Continue reading...</a></p>
	                </div>
	            </div>
	        </div>
	    </div>
	        
	    <div class="row">
	        <div class="col-12">
	                <div class="p-3 mb-3 bg-light rounded">
	                <h4>About</h4>
	                <p class="mb-0"><span class="font-italic">I think, keeping a blog and journal is a great way to reflect my core values and meaning of life.</span> So, this is my Blog, please enjoy!</p>
	            </div>
	        </div>
	    </div>
			
	    </div>
    </div>
{% endblock %}
	

blog/templates/blog/layout.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
	<head>
		<meta charset="UTF-8">
		<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
		<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
		<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
		<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
		<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>
		<link rel="stylesheet" type="text/css" href="{% static 'blog/styles.css' %}">
        <title>Daniel's blog</title>
    </head>
    <body>
        <div class="container">
            <header class="sticky-top">
	            <div class="row flex-nowrap justify-content-between align-items-center bg-dark">
	                <div class="col-4 text-center">
	                    <h2 class="text-white" href="#">Daniel's blog</h2>
	                </div>
	            </div>
	            <nav class="navbar navbar-expand-lg navbar-light bg-light">
	                <a class="navbar-brand mx-auto" href="#">Categories:</a>
	                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
	                    <span class="navbar-toggler-icon"></span>
	                </button>
	                
	                <div class="collapse navbar-collapse" id="navbarSupportedContent">
	                    <div class="navbar-nav mx-auto">
	                        <a class="p-2 text-muted" href="#">Technology</a>
	                        <a class="p-2 text-muted" href="#">Business</a>
	                        <a class="p-2 text-muted" href="#">Opinion</a>
	                        <a class="p-2 text-muted" href="#">Science</a>
		                    <a class="p-2 text-muted" href="#">Mathematics</a>
	                    </div>
	                </div>
	            </nav>
			</header>
			{% block content %}{% endblock %}
            <footer>
				<div class="container text-center text-white">
					© Copyright 2020 Daniel Syahputra
				</div>
			</footer>
        </div>
    </body>
		

story_1/templates/story_1/index.html
{% extends "story_1/layout.html" %}
{% load static %}
{% block body %}
    <div class="wrapper">
        <div class="left">
            <img src="{% static '/story_1/images/MX21.jpg' %}" alt="photo-profile" width="80%">
            <h3>Daniel Syahputra Purba</h3>
            <p>Tech Enthusiast | Sophomore Student @ University of Indonesia</p>
            <div class="social-media">
                <a href="https://www.instagram.com/danielsyahputra13/" target="_blank"><img src="{% static '/story_1/images/instagram.svg' %}"></a>
                <a href="https://www.linkedin.com/in/daniel-syahputra-purba-940999175/" target="_blank"><img src="{% static '/story_1/images/linkedin.svg' %}"></a>
                <a href="mailto:dnlshp@gmail.com"><img src="{% static '/story_1/images/gmail.svg' %}"></a>
                <a href="https://github.com/danielsyahputra13" target="_blank"><img src="{% static '/story_1/images/github.svg' %}"></a>
            </div>
        </div>
        <div class="right">
            <h3>Information</h3>
            <div class="description">
                <div class="info">
                    <div class="data">
                        <h4>NPM</h4>
                        <p>1906398793</p>
                    </div>
                    <div class="data">
                        <h4>Angkatan</h4>
                        <p>2019</p>
                    </div>
                    <div class="data">
                        <h4>Tempat Kuliah</h4>
                        <p>Universitas Indonesia</p>
                    </div>
                    <div class="data">
                        <h4>Hobi</h4>
                        <p>Programming, Musik, Berenang</p>
                    </div>
                    <div class="data">
                        <h4>Deskripsi Tentang Saya</h4>
                        <p>
                            Saat ini Daniel sedang menjalani tingkat 2 di Fasilkom UI.<br>
                            Daniel memiliki ketertarikan di Bidang STEM (Science Technology Engineering and Math).
                        </p>
                    </div>
                    <div class="data">
                        <h4>Riwayat Pendidikan</h4>
                        <p>SD St.Antonius VI Medan</p>
                        <p>SMP Negeri 3 Medan</p>
                        <p>SMA Negeri 1 Raya</p>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

story_1/templates/story_1/layout.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
	<link href='https://fonts.googleapis.com/css?family=Libre+Baskerville:400,700,400italic' rel='stylesheet' type='text/css'>
	<link href="https://fonts.googleapis.com/css2?family=Josefin+Sans&family=Roboto&display=swap" rel="stylesheet">
	<link rel="stylesheet" href="{% static 'story_1/styles.css' %}">
    <title>Story 1 | About me</title>
</head>
<body>
	{% block body %}
	{% endblock %}
</body>
</html>

story_4/templates/story_4/index.html
{% extends 'story_4/layout.html' %}
{% load static %}
{% block header %}
{% include 'story_4/navbar.html' %}
{% endblock %}
{% block content %}

    <!--Landing page-->
    <section id="landing-page">
        <div class="container h-100">
            <div class="row h-100 align-items-center justify-content-center text-center">
                <div class="col-lg-10 align-self-end">
                    <h3 class="font-italic font-weight-bold landing-page-text">Hey, I'm</h3>
                    <h1 class="font-weight-bold landing-page-text">Daniel Syahputra</h1>
                    <hr>
                </div>
                <div class="col-lg-8 align-self-baseline">
                    <p class="font-italic text-white font-weight-light">"Anyone who stops learning is old, whether at twenty or eighty" – Henry Ford</p>
                    <a class="btn btn-secondary btn-xl " href="{% url 'story_4:index' %}#about-me">Get Started</a>
                </div>
            </div>
        </div>
    </section>

    <main>
        <div class="container">
            <!--about me-->
            <section id="about-me">
                <div class="row justify-content-center">
                    <div class="col-lg-8 text-center info">
                        <h1 class="font-weight-bold">About me</h1>
                        <hr>
                    </div>
                    <div class="col-lg-6 col-md-6 col-sm-12">
                        <img class=".img-thumbnail w-50 mx-auto d-block images" src="{% static 'story_4/images/MX21.jpg' %}">
                    </div>
                    <div class="col-lg-6 col-md-6 col-sm-12">
                        <h2>Description</h2>
                        <p>I'm a Computer Science student at University of Indonesia. I have interests in STEM (Science, Technology, Engineer, and Mathematics). My focuses now is on all of the fields that related to Big data like Business Intelligence, Machine Learning, etc.
                        </p>
                    </div>
                </div>
            </section>

            <!--Section: Experience-->
            <section id="experiences">
                <div class="row justify-content-center">
                    <div class="col-lg-8 text-center info">
                        <h1 class="font-weight-bold">My Journey</h1>
                        <hr>
                    </div>
                </div>
                <div class="row">
                    <div class="col-lg-6 col-md-6 col-sm-12">
                        <img class=".img-thumbnail w-50 mx-auto d-block images" src="{% static 'story_4/images/logo-universitas-indonesia.png' %}">
                    </div>
                    <div class="col-lg-6 col-md-6 col-sm-12">
                        <h2>Teaching Assistant of Calculus 1</h2>
                        <h5>Aug 2020 - Presents</h5>
                        <p>A teaching assistant, also known as a TA, handles many of the same tasks as the lecturer do. TAs may teach classes, work with students in laboratories, grade papers, and projects.</p>
                    </div>

                    <!--DDP-0-->
                    <div class="col-lg-6 col-md-6 col-sm-12 info">
                        <img class=".img-thumbnail w-50 mx-auto d-block images" src="{% static 'story_4/images/maung.png' %}">
                    </div>
                    <div class="col-lg-6 col-md-6 col-sm-12 info">
                        <h2>Student Mentor - Foundation of Programming 0</h2>
                        <h5>Aug 2020 - Sept 2020</h5>
                        <p>Foundation of Programming 0 is an event from Fasilkom UI which held by students and followed by freshman student in Fasilkom as an introduction to programming.</p>
                    </div>


                    <!--BI Sistem-->
                    <div class="col-lg-6 col-md-6 col-sm-12 info">
                        <img class=".img-thumbnail w-50 mx-auto d-block images" src="{% static 'story_4/images/Sistem_fasilkom.jpg' %}">
                    </div>
                    <div class="col-lg-6 col-md-6 col-sm-12 info">
                        <h2>Business Intelligence Team</h2>
                        <h5>Feb 2020 - Aug 2020</h5>
                        <p>Business Intelligence is one of SIG (Special
        Interest Group) in SISTEM Fasilkom UI which
        has an interest in using data with the objective
        to support business development. </p>

                    </div>

                    <!--Betis-->
                    <div class="col-lg-6 col-md-6 col-sm-12 info">
                        <img class=".img-thumbnail w-50 mx-auto d-block images" src="{% static 'story_4/images/betis_fasilkom.png' %}">
                    </div>
                    <div class="col-lg-6 col-md-6 col-sm-12 info">
                        <h2>Mathematics Tutor</h2>
                        <h5>Feb 2020 - May 2020</h5>
                        <p>BETIS Fasilkom UI is a Study Guidance from Fasilkom UI that has a mission to help the student that will be graduated from Senior High School. As a mathematic tutor, I have a duty to teach my peer to prepare their exam at University especially in mathematics.</p>
                    </div>

                </div>
            </section>

            <!--Section: Education-->
            <section id="education">
                <div class="row justify-content-center">
                    <div class="col-lg-8 text-center info">
                        <h1 class="font-weight-bold">Education</h1>
                        <hr>
                    </div>
                </div>
                <div class="row">
                    <div class="col-lg-6 col-md-6 col-sm-12">
                            <img class=".img-thumbnail w-50 mx-auto d-block images" src="{% static 'story_4/images/logo_fasilkom.png' %}">
                    </div>
                    <div class="col-lg-6 col-md-6 col-sm-12">
                        <h2>University of Indonesia</h2>
                        <h5>2019 - 2023</h5>
                        <h5>Faculty of Computer Science, Information System Major</h5>
                        <p>Computer Science graduates are generally sought by companies that require the expertise of system analysts, IT managers, web developers, and software engineers.</p>
                    </div>
                </div>
            </section>

            <!-- Project -->
            <section id="project">
                <div class="row justify-content-center">
                    <div class="col-lg-8 text-center info">
                        <h1 class="font-weight-bold">Project</h1>
                        <hr>
                    </div>
                </div>
                <div class="row justify-content-center">
                    <div class="col-md-4 mb-3 mb-md-0">
                        <div class="card py-4 h-100  bg-light mb-3">
                            <div class="card-body text-center">
                                <h4 class="m-0">Story 1</h4>
                                <hr class="my-4" />
                                <a href="./story_1/" target="_blank">Open</a>
                            </div>
                        </div>
                    </div>

                    <div class="col-md-4 mb-3 mb-md-0">
                        <div class="card py-4 h-100 bg-light mb-3">
                            <div class="card-body text-center">
                                <h4 class="m-0">Cek dan Tambah Matkul</h4>
                                <hr class="my-4" />
                                <a href="http://matkul-pacil.herokuapp.com/" target="_blank">Open</a>
                            </div>
                        </div>
                    </div>
                    <div class="col-md-4 mb-3 mb-md-0">
                        <div class="card py-4 h-100 bg-light mb-3">
                            <div class="card-body text-center">
                                <h4 class="m-0">Buku Kegiatan</h4>
                                <hr class="my-4" />
                                <a href="https://story-daniel.herokuapp.com/" target="_blank">Open</a>
                            </div>
                        </div>
                    </div>
                </div>
            </section>

            <!--Section: Believe-system-->
            <section id="believe-system">
                <div class="row justify-content-center">
                    <div class="col-lg-8 text-center info">
                        <h1 class="font-weight-bold">My Believe System</h1>
                        <hr>
                    </div>
                    <div class="col-lg-8 text-center">
                        <h4><a href="https://www.youtube.com/watch?v=JC82Il2cjqA" target="_blank">You can learn anything</a></h4>
                        <h4><a href="https://www.weforum.org/agenda/2018/01/the-secret-to-lifelong-success-is-lifelong-learning" target="_blank">Learning for a lifetime</a></h4>
                    </div>
                </div>
            </section>

            <!--Section: Feedback-->
            <section id="feedback">
                <div class="row justify-content-center">
                    <div class="col-lg-8 text-center info">
                        <h1 class="font-weight-bold">Let me know if you need help</h1>
                        <hr>
                    </div>
                </div>
                <form>
                    <div class="form-group">
                        <label for="formGroupExampleInput">Name</label>
                        <input type="text" class="form-control" id="formGroupExampleInput" placeholder="Your Name">
                    </div>
                    <div class="form-group">
                        <label for="formGroupExampleInput2">Email</label>
                        <input type="text" class="form-control" id="formGroupExampleInput2" placeholder="Your Email">
                    </div>
                </form>
                <div class="form-group">
                    <label for="exampleFormControlTextarea1">Please, leave your feedback below</label>
                    <textarea class="form-control" id="exampleFormControlTextarea1" rows="3"></textarea>
                </div>
                <div class="form-group row">
                    <div class="col-sm-10">
                        <button type="submit" class="btn btn-primary">Submit</button>
                    </div>
                </div>
            </section>

        </div>
    </main>

    <!--Contact-->
    <section id="contact" class="bg-black">
        <div class="container">
            <div class="row justify-content-center">
                <div class="col-lg-8 text-center info">
                    <h1 class="font-weight-bold">Let's Get in Touch</h1>
                    <hr>
                </div>
            </div>
            <div class="row">
                <div class="col-md-4 mb-3 mb-md-0">
                    <div class="card py-4 h-100">
                        <div class="card-body text-center">
                            <img src="{% static 'story_4/images/linkedin.svg' %}" width="50px">
                            <h4 class="m-0">Linkedin</h4>
                            <hr class="my-4" />
                            <a href="https://www.linkedin.com/in/daniel-syahputra-purba-940999175/">Link</a>
                        </div>
                    </div>
                </div>
                <div class="col-md-4 mb-3 mb-md-0">
                    <div class="card py-4 h-100">
                        <div class="card-body text-center">
                            <img src="{% static 'story_4/images/instagram.svg' %}" width="50px">
                            <h4 class="m-0">Instagram</h4>
                            <hr class="my-4" />
                            <a href="https://www.instagram.com/danielsyahputra13/">Link</a>
                        </div>
                    </div>
                </div>
                <div class="col-md-4 mb-3 mb-md-0">
                    <div class="card py-4 h-100">
                        <div class="card-body text-center">
                            <img src="{% static 'story_4/images/github.svg' %}" width="50px">
                            <h4 class="m-0">Github</h4>
                            <hr class="my-4" />
                            <a href="https://github.com/danielsyahputra13">Link</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
{% endblock %}

story_4/templates/story_4/layout.html
{% load static %}
<!DOCTYPE html>
    <html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
        <link rel="stylesheet" type="text/css" href="{% static 'story_4/styles.css' %}">
        <link href="https://fonts.googleapis.com/css2?family=Arvo&display=swap" rel="stylesheet">
        <link href="https://fonts.googleapis.com/css2?family=Dosis&display=swap" rel="stylesheet">
        <link href="https://fonts.googleapis.com/css2?family=Roboto&display=swap" rel="stylesheet">
        <link href="https://fonts.googleapis.com/css2?family=Odibee+Sans&display=swap" rel="stylesheet">
        <!--Adding my logo to title bar-->
        <link rel="shortcut icon" href="{% static 'story_4/images/logo-daniel.ico' %}">
        <title>Portfolio Website</title>
        <script>
            window.onscroll =() => {
                if (window.innerHeight + window.scrollY >= document.querySelector('#experiences').offsetHeight) {
                    document.querySelector('.navbar').style.background = '#212529';
                } else {
                    document.querySelector('.navbar').style.backgroundColor = 'transparent';
                }
            }
        </script>
    </head>
    <body>
        <!--Header-->
        {% block header %}{% endblock %}

        <!--Fill content-->
        {% block content %}
        {% endblock %}

        <!--Footer-->
        <footer>
            <div class="container text-center text-white">
                © Copyright 2020 Daniel Syahputra
            </div>
        </footer>

        <!--Javascript from Bootstrap-->
        <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>
    </body>
</html>

story_4/templates/story_4/navbar.html
{% load static %}
<!--Header section-->
<header>
    <!--Create navbar-->
    <nav class="navbar navbar-expand-lg navbar-dark fixed-top scrolling-navbar">
        <div class="container">
            <!--Navbar brand-->
            <a class="navbar-brand font-weight-bold text-white"><img src="{% static 'story_4/images/logo-daniel.png' %}" width="50px"> | Daniel Syahputra</a>

            <!--Collapse button if we shrink to smaller screen-->
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#basicExampleNav" aria-controls="basicExampleNav" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="basicExampleNav">

                <!-- Links -->
                <ul class="navbar-nav ml-auto smooth-scroll">
                    <li class="nav-item">
                        <a class="nav-link font-weight-bold" href="{% url 'story_4:index' %}#landing-page">Home</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link font-weight-bold" href="{% url 'story_4:index' %}#about-me">About</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link font-weight-bold" href="{% url 'story_4:index' %}#experiences">Experiences</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link font-weight-bold" href="./blog/" target="_blank">Blog</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link font-weight-bold" href="{% url 'story_4:index' %}#contact">Contact</a>
                    </li>
                </ul>

            </div>
        </div>
    </nav>
</header>